# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BSShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BSShop
pod 'RealmSwift'
pod 'Alamofire'
pod 'Swinject'
pod 'SDWebImage', '~> 5.0'
pod 'SimpleImageViewer', '~> 1.1.1'
pod 'SwiftLint'
pod 'Bond'

end
